### ISSUE TITLE
Repair only works sometime

### ISSUE THREAD

**Issue by puixdk** [ESX-Org/esx_mecanojob#27]
For some people the repair work, but other it seems not to work. 
It will be fixed for mechanics but not the car user. This is 50/50, if repair work right now..

**Comment by lilfuchs** [comment]
this is a fivem sync issue bug. Have mechanics get in the driver seat first before letting the car owner back in it

**Comment by lilfuchs** [comment]
Also duplicate of #24

**Comment by ElPumpo** [comment]
Duplicate of #24 open your eyes
