### ISSUE TITLE
see no one in the garage..

### ISSUE THREAD

**Issue by mangamaniacs2064** [ESX-Org/esx_mecanojob#29]
i cant see anyone in the garage.
i go to the marker on the map then enter los santos custom garage... there is no one or no purple spot.
i installed the required files.. still nothing...

**Comment by xsunnusx** [comment]
you have to sen urself or somebody to be mechanic, and in esx_lscustoms set mechanojob = true if you want only mechanic to tune and work in lscustoms,
it's a job not a mechanic for ur customs, someone has to be mechano

**Comment by ElPumpo** [comment]
update esx
