### ISSUE TITLE
How to get the money to go to player not society

### ISSUE THREAD

**Issue by chdo888** [ESX-Org/esx_mecanojob#30]
How can I get this mod when a player does the missions the money go to society instead of the player. is there a way for the mod to pay the player instead of society. 
Thanks

**Comment by ElPumpo** [comment]
When doing NPC missions? [Here](https://github.com/ESX-Org/esx_mecanojob/blob/714a16c60bb31dbe12a342e1aebdcadaceb4e5a6/server/main.lua#L227)
