### ISSUE TITLE
I press E and nothing happens

### ISSUE THREAD

**Issue by radiodrag** [ESX-Org/esx_mecanojob#35]
I get to the blip where it tells me to press E to open the menu, but there's no menu

**Comment by CryptoGenics** [comment]
Same thing here popup says press E to open menu but nothing responds to E press on Craft or Action circles.

**Comment by Timo972** [comment]
I've gotten the same issue

**Comment by Radeon911QC** [comment]
Same thing! We need help!

**Comment by ElPumpo** [comment]
Fixed now. If you have the same problem then you can use emojis instead of spamming the thread with adding comments like 'same thing'
