### ISSUE TITLE
identity enabled on esx_society error when promoting people

### ISSUE THREAD

**Issue by ddh3** [ESX-Org/esx_mecanojob#5]
When esx_society has Config.EnableESXIdentity  = true 
 
when trying to promote someone, this error occurs. 

[   5826156] Error running call reference function for resource esx_society: server/main.lua:282: attempt to index a nil value (local 'xPlayer')
[   5826172] stack traceback:
[   5826172] 	server/main.lua:282: in local 'ref'
[   5826172] 	citizen:/scripting/lua/scheduler.lua:277: in function <citizen:/scripting/lua/scheduler.lua:268>
[   5826203] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
[   5826203] stack traceback:
[   5826203] 	[C]: in function 'error'
[   5826219] 	citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
[   5826219] 	citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
[   5826219] 	citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
[   5826234] 	citizen:/scripting/lua/scheduler.lua:338: in field '?'
[   5826234] 	server/functions.lua:48: in field 'TriggerServerCallback'
[   5826234] 	server/common.lua:73: in upvalue 'handler'
[   5826250] 	citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
[   5826250] stack traceback:
[   5826250] 	[C]: in function 'error'
[   5826265] 	citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
[   5826265] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by ElPumpo** [comment]
Was fixed in 2a60ff3f1fb56fea1204ca61deb7cc4992cbc00c
